# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
ko_fi: dreamhollow4219 # Replace with a single Ko-fi username
