# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dreamhollow/Documents/github/cmakeeasy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dreamhollow/Documents/github/cmakeeasy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dreamhollow/Documents/github/cmakeeasy/CMakeFiles /home/dreamhollow/Documents/github/cmakeeasy//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dreamhollow/Documents/github/cmakeeasy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cmakeeasy

# Build rule for target.
cmakeeasy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cmakeeasy
.PHONY : cmakeeasy

# fast build rule for target.
cmakeeasy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmakeeasy.dir/build.make CMakeFiles/cmakeeasy.dir/build
.PHONY : cmakeeasy/fast

#=============================================================================
# Target rules for targets named copy_resources

# Build rule for target.
copy_resources: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 copy_resources
.PHONY : copy_resources

# fast build rule for target.
copy_resources/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copy_resources.dir/build.make CMakeFiles/copy_resources.dir/build
.PHONY : copy_resources/fast

src/AltString.o: src/AltString.cpp.o
.PHONY : src/AltString.o

# target to build an object file
src/AltString.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmakeeasy.dir/build.make CMakeFiles/cmakeeasy.dir/src/AltString.cpp.o
.PHONY : src/AltString.cpp.o

src/AltString.i: src/AltString.cpp.i
.PHONY : src/AltString.i

# target to preprocess a source file
src/AltString.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmakeeasy.dir/build.make CMakeFiles/cmakeeasy.dir/src/AltString.cpp.i
.PHONY : src/AltString.cpp.i

src/AltString.s: src/AltString.cpp.s
.PHONY : src/AltString.s

# target to generate assembly for a file
src/AltString.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmakeeasy.dir/build.make CMakeFiles/cmakeeasy.dir/src/AltString.cpp.s
.PHONY : src/AltString.cpp.s

src/Application.o: src/Application.cpp.o
.PHONY : src/Application.o

# target to build an object file
src/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmakeeasy.dir/build.make CMakeFiles/cmakeeasy.dir/src/Application.cpp.o
.PHONY : src/Application.cpp.o

src/Application.i: src/Application.cpp.i
.PHONY : src/Application.i

# target to preprocess a source file
src/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmakeeasy.dir/build.make CMakeFiles/cmakeeasy.dir/src/Application.cpp.i
.PHONY : src/Application.cpp.i

src/Application.s: src/Application.cpp.s
.PHONY : src/Application.s

# target to generate assembly for a file
src/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmakeeasy.dir/build.make CMakeFiles/cmakeeasy.dir/src/Application.cpp.s
.PHONY : src/Application.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmakeeasy.dir/build.make CMakeFiles/cmakeeasy.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmakeeasy.dir/build.make CMakeFiles/cmakeeasy.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmakeeasy.dir/build.make CMakeFiles/cmakeeasy.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Manager.o: src/Manager.cpp.o
.PHONY : src/Manager.o

# target to build an object file
src/Manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmakeeasy.dir/build.make CMakeFiles/cmakeeasy.dir/src/Manager.cpp.o
.PHONY : src/Manager.cpp.o

src/Manager.i: src/Manager.cpp.i
.PHONY : src/Manager.i

# target to preprocess a source file
src/Manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmakeeasy.dir/build.make CMakeFiles/cmakeeasy.dir/src/Manager.cpp.i
.PHONY : src/Manager.cpp.i

src/Manager.s: src/Manager.cpp.s
.PHONY : src/Manager.s

# target to generate assembly for a file
src/Manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmakeeasy.dir/build.make CMakeFiles/cmakeeasy.dir/src/Manager.cpp.s
.PHONY : src/Manager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... copy_resources"
	@echo "... cmakeeasy"
	@echo "... src/AltString.o"
	@echo "... src/AltString.i"
	@echo "... src/AltString.s"
	@echo "... src/Application.o"
	@echo "... src/Application.i"
	@echo "... src/Application.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Manager.o"
	@echo "... src/Manager.i"
	@echo "... src/Manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

